import type { Report, UserProfile, ReportData } from "./types";

export const DEMO_PROFILE: UserProfile = {
  token: "demo",
  email: "demo@mybc.app",
  name: "Fanny",
  birth_full_name: "Fanny Demo",
  birth_date: "1998-06-10",
  birth_time: "08:03",
  birth_place: "Verviers, Belgium",
  birth_lat: 50.5895,
  birth_lng: 5.8635,
  language: "English",
  status: "active",
  created_at: "2026-01-01T00:00:00Z",
};

const DATA: ReportData = {
  // ── Chart ─────────────────────────────────────────────────────────
  chart_signs: [
    { sign: "Aries",       glyph: "♈", planets: ["Jupiter", "Saturn"], count: 2 },
    { sign: "Taurus",      glyph: "♉", planets: [],                    count: 0 },
    { sign: "Gemini",      glyph: "♊", planets: ["Sun", "Mercury"],    count: 2 },
    { sign: "Cancer",      glyph: "♋", planets: ["ASC", "Venus"],      count: 2 },
    { sign: "Leo",         glyph: "♌", planets: ["Moon", "NN"],        count: 2 },
    { sign: "Virgo",       glyph: "♍", planets: [],                    count: 0 },
    { sign: "Libra",       glyph: "♎", planets: ["Mars"],              count: 1 },
    { sign: "Scorpio",     glyph: "♏", planets: [],                    count: 0 },
    { sign: "Sagittarius", glyph: "♐", planets: ["Pluto"],             count: 1 },
    { sign: "Capricorn",   glyph: "♑", planets: [],                    count: 0 },
    { sign: "Aquarius",    glyph: "♒", planets: ["Uranus", "Neptune", "SN"], count: 3 },
    { sign: "Pisces",      glyph: "♓", planets: ["MC"],                count: 1 },
  ],

  chart_distribution: {
    elements: [
      { l: "Air",   v: 40, gloss: "thought, ideas, communication" },
      { l: "Fire",  v: 35, gloss: "inspiration, drive, expression" },
      { l: "Water", v: 20, gloss: "feeling, intuition, memory" },
      { l: "Earth", v: 5,  gloss: "matter, body, structure" },
    ],
    modes: [
      { l: "Cardinal", v: 45, gloss: "initiating, starting, leading" },
      { l: "Fixed",    v: 30, gloss: "sustaining, building, holding" },
      { l: "Mutable",  v: 25, gloss: "adaptable, responsive, fluid" },
    ],
    summary: {
      plain:  "Air-and-fire dominant. You live in thought and inspiration. Your body and material life are where the practice lives.",
      expert: "Air 40% / Fire 35% · Cardinal 45%. Ten planets cluster in 10th / 12th / ASC axis. Earth deficit demands daily embodiment work.",
    },
  },

  // ── Hub ───────────────────────────────────────────────────────────
  today_default: {
    moonSign: "Sagittarius",
    do:    "Expand. Brainstorm. Think big.",
    avoid: "Overcommitting. Scattered plans.",
    energy: 8,
  },

  // ── Daily protocol ────────────────────────────────────────────────
  daily_protocol: {
    morning: {
      label: "Morning",
      start: "06:30",
      intro: {
        plain:  "Your nervous system needs a soft start. Land in your body before the day asks anything of you.",
        expert: "Cancer ASC + 12H Venus = sensitive morning architecture. Wake before the world reaches in.",
      },
      items: [
        { time: "06:30", action: "Wake slowly · stay in bed",         sub: "One hand on heart, one on belly · 10 slow breaths · one-word intention",    source: "Cancer ASC · lunar waking" },
        { time: "06:35", action: "Water + sea salt + lemon",          sub: "500 ml room-temperature filtered water — restores overnight minerals",        source: "Libra Mars · adrenal axis" },
        { time: "06:45", action: "4-7-8 breathing · 5 rounds",        sub: "Then 5 min alternate-nostril (Nadi Shodhana)",                               source: "GABA · Moon–Neptune opposition" },
        { time: "07:05", action: "Pilates or slow flow yoga or walk",  sub: "20–25 min · no high-intensity · Mars in Libra needs rhythm, not aggression", source: "Mars ♎ · Libra Mars 4H" },
        { time: "07:30", action: "Journaling — Leo Moon prompts",      sub: '"What does my heart want to be seen for today?" · 5 min',                   source: "Moon ♌ 12H · NN Leo" },
        { time: "07:35", action: "10 min morning sunlight",           sub: "Eyes and skin · no sunglasses · resets circadian rhythm and mood",           source: "12H melatonin excess · Cancer ASC" },
      ],
    },
    day: {
      label: "Day",
      start: "09:30",
      intro: {
        plain:  "Your sharpest hours. Build, write, decide. Pull the unseen into shape.",
        expert: "Mercury 12H output peaks 09:30–11:30. Saturn-Jupiter MC favors structuring others in the 14:30 window.",
      },
      items: [
        { time: "09:30", action: "Deep cognitive work block",          sub: "Writing, strategy, complex analysis · 75–90 min uninterrupted",  source: "Mercury ♊ 12H · interior focus" },
        { time: "11:00", action: "Movement break — outside",          sub: "10 min walk · no phone · window open",                          source: "Gemini · air-dominant chart" },
        { time: "11:30", action: "Calls, meetings, negotiations",     sub: "Best window for verbal output",                                 source: "Mercury-hour energy" },
        { time: "13:30", action: "Proper lunch — seated and slow",    sub: "Never at the desk · audio fine, work is not",                   source: "Cancer ASC · gut axis" },
        { time: "15:00", action: "Secondary focus — editing/details", sub: "Good window for execution and refinement",                      source: "Saturn ♈ 10H · discipline" },
        { time: "16:30", action: "Walk or lie-down · 15 min",        sub: "Mandatory reset before the evening phase",                      source: "Libra Mars · adrenal recovery" },
        { time: "17:00", action: "Relational conversations",         sub: "Social connection, partnerships, Venus-hour energy",            source: "Venus ♋ 12H · 7H" },
      ],
    },
    evening: {
      label: "Evening",
      start: "20:00",
      intro: {
        plain:  "Soften the edges. The night is for digestion — of food, of feeling, of what was said.",
        expert: "Pisces MC + 12H Moon = symbolic-night processing. Stimulus must lower before 21:00 or the dream architecture collapses.",
      },
      items: [
        { time: "19:30", action: "Light dinner",                     sub: "Bone broth · white fish · roasted root vegetables · before 20:00",       source: "Cancer ASC · 3 h before sleep" },
        { time: "20:30", action: "Digital sunset",                   sub: "Phone on airplane mode · in another room if possible",                     source: "Moon–Neptune opposition · 12H" },
        { time: "21:00", action: "Magnesium bath · 3–4×/week",      sub: "Hot bath · 2 cups Epsom salts · lavender oil · 20 min · cool rinse finish", source: "Cancer/12H water axis" },
        { time: "21:30", action: "Restorative yoga or legs-up-wall", sub: "10 min · releases lymphatic stagnation (Cancer/Libra axis)",               source: "Lymphatic + adrenal recovery" },
        { time: "21:45", action: "Humming or chanting · 5 min",     sub: "Activates vagus nerve via vocal cords",                                     source: "Gemini · respiratory axis" },
        { time: "22:00", action: "Brain-dump journaling",            sub: "Get the Gemini mind out of your head and onto paper",                       source: "Mercury 12H · rumination pattern" },
        { time: "22:30", action: "Sleep",                            sub: "17–18 °C · total darkness · no light · 8 hours target",                    source: "Moon 12H · primary healing modality" },
      ],
    },
  },

  // ── Strengths ─────────────────────────────────────────────────────
  strengths: [
    {
      title: "Visionary\nsynthesis",
      tag: "Strength · 01 of 15",
      blurb: "Seeing a future others haven't yet imagined — and drawing the bridge from here to there.",
      practice: ["Translating abstract patterns into concrete artifacts.", "Holding several disciplines in mind simultaneously without losing coherence."],
      activated: "Time, space, and uncluttered input — quiet mornings before the world reaches in.",
      source: ["☉ Sun ♊ 10H", "♃ Jupiter ♈ 10H", "♇ Pluto trine ♃"],
    },
    {
      title: "Symbolic\ncognition",
      tag: "Strength · 02 of 15",
      blurb: "Reading patterns, archetypes, and hidden meaning others miss — the layer beneath the literal.",
      practice: ["Making unusual connections between distant domains.", "Seeing the thread that runs through architecture, AI, and ancestral work as one language."],
      activated: "Solitude and slow, unhurried observation — the 12th-house channel.",
      source: ["☿ Mercury ♊ 12H", "♆ Neptune trine ☿", "12H stellium"],
    },
    {
      title: "Magnetic\npresence",
      tag: "Strength · 03 of 15",
      blurb: "People feel drawn to you without knowing why. It is not performance — it is embodied truth.",
      practice: ["Entering a room and instantly reading its emotional field.", "Being fully present with one person at a time."],
      activated: "Self-acceptance and physical grounding — when you are at ease in your body.",
      source: ["♀ Venus ♋ near ASC", "☽ Moon ♌", "♇ Pluto trine"],
    },
    {
      title: "Creative\ncourage",
      tag: "Strength · 04 of 15",
      blurb: "Starting things no one else dares to start — building visible careers in unconventional terrain.",
      practice: ["Launching a product before the market knows it needs it.", "Staying in the arena when the audience isn't yet there."],
      activated: "A deadline and a witness — Saturn in 10H needs accountability to activate.",
      source: ["♃ Jupiter ♈ 10H", "♄ Saturn ♈ 10H", "Aries stellium"],
    },
    {
      title: "Healing\npresence",
      tag: "Strength · 05 of 15",
      blurb: "People tell you things they haven't told anyone. This is not accident — it is the 12th house working.",
      practice: ["Holding space without needing to fix.", "Being the person others call at 2 AM."],
      activated: "Stillness. When you slow down, the field opens.",
      source: ["☽ Moon 12H", "♀ Venus 12H", "☿ Mercury 12H"],
    },
    {
      title: "Multi-domain\nfluency",
      tag: "Strength · 06 of 15",
      blurb: "Moving between architecture, AI, mysticism, and business without losing coherence or credibility.",
      practice: ["Explaining quantum computing to a shaman and sacred geometry to a developer.", "Being the translator between worlds."],
      activated: "Permission to weave — when you stop apologizing for the range.",
      source: ["☉ Sun ♊", "☿ Mercury ♊", "Gemini emphasis"],
    },
    {
      title: "Pattern-finding\nacross time",
      tag: "Strength · 07 of 15",
      blurb: "Finding the thread that runs through generations, cycles, and epochs — the invisible architecture of time.",
      practice: ["Noticing the same karmic pattern playing out in a family across three generations.", "Reading a historical cycle and mapping its echo on the present."],
      activated: "Research time and enough silence to listen to the pattern.",
      source: ["♇ Pluto ♐ 5H trine ♃", "12H archive", "NN ♌ 12H"],
    },
    {
      title: "Aesthetic\nintelligence",
      tag: "Strength · 08 of 15",
      blurb: "You see when something is off visually before you can articulate why. This is data.",
      practice: ["Redesigning a space, a brand identity, a slide deck — in minutes.", "Knowing what a person needs to wear to own a room."],
      activated: "Travel and beauty exposure — novelty wakes the aesthetic eye.",
      source: ["♀ Venus ♋", "♂ Mars ♎", "MC ♓"],
    },
    {
      title: "Resilience\nafter collapse",
      tag: "Strength · 09 of 15",
      blurb: "Disruption as redirection — you rebuild faster than most, and the rebuilt version is always truer.",
      practice: ["Turning a failed launch into a pivot that actually fits.", "Using loss as material."],
      activated: "Adversity, paradoxically. The pressure is the catalyst.",
      source: ["♇ Pluto ♐ 5H", "♄ Saturn anaretic 10H", "Cardinal dominance"],
    },
    {
      title: "Teaching through\nmetaphor",
      tag: "Strength · 10 of 15",
      blurb: "Complex ideas become felt and understood — not just known — when you teach them.",
      practice: ["Making astrology actionable for someone who thinks it's superstition.", "Explaining AI systems as living ecosystems."],
      activated: "A receptive audience that isn't yet convinced.",
      source: ["☿ Mercury 12H", "♃ Jupiter 10H", "Gemini Sun"],
    },
    {
      title: "Leadership\nby radiance",
      tag: "Strength · 11 of 15",
      blurb: "You lead by being, not by commanding. People follow your example before you give any instruction.",
      practice: ["The room shifting when you shift.", "Junior people mirroring your energy without realizing it."],
      activated: "Creative authority — when you own your expertise without apology.",
      source: ["☽ Moon ♌", "NN ♌ 12H", "☉ Sun 10H"],
    },
    {
      title: "Entrepreneurial\ninstinct",
      tag: "Strength · 12 of 15",
      blurb: "You see market gaps and unconventional paths before others name them.",
      practice: ["Building a product category that doesn't yet exist.", "Recognizing the monetization angle inside a creative project."],
      activated: "Freedom and a clear constraint — the paradox of Saturn + Jupiter.",
      source: ["♈ Aries stellium 10H", "♅ Uranus 8H", "Jupiter-Saturn conj."],
    },
    {
      title: "Emotional\nweather-reading",
      tag: "Strength · 13 of 15",
      blurb: "You feel the room within seconds. This is data — not noise, not weakness.",
      practice: ["Naming what everyone is feeling but no one is saying.", "Adjusting a presentation in real time because you sensed the energy shift."],
      activated: "Quiet observation time before you enter the room.",
      source: ["☽ Moon opp ♆", "Cancer ASC", "12H stellium"],
    },
    {
      title: "Long-term\narchitecture",
      tag: "Strength · 14 of 15",
      blurb: "You build structures — businesses, products, lives — designed to last decades, not seasons.",
      practice: ["Writing a 10-year vision that actually tracks.", "Designing a product with the exit built into the foundation."],
      activated: "Patience — and the willingness to let the structure reveal itself.",
      source: ["♄ Saturn MC", "Architectural training", "Cardinal + Fixed blend"],
    },
    {
      title: "Ancestral\nbridge",
      tag: "Strength · 15 of 15",
      blurb: "You carry forward what your lineage couldn't finish. This is not a burden — it is a mandate.",
      practice: ["Doing the work your parents' generation couldn't name.", "Making visible what was hidden for generations."],
      activated: "Remembrance and ritual — when you consciously acknowledge what you carry.",
      source: ["☽ Moon 12H", "Cancer ASC", "NN ♌ 12H"],
    },
  ],

  // ── Careers ───────────────────────────────────────────────────────
  career_mission: {
    plain:  "Bring the light of the hidden self into the visible world — from a place of inner authority, not external approval.",
    expert: "☿ Mercury ♊ 12H + ♄♃ ♓ MC. Translator-architect. Esoteric content → built form. NN ♌ 12H says the mission must feel like a temple, not a hospital.",
  },

  careers: [
    {
      n: "01",
      title: "AI consultant for creative industries",
      sub: "Translator of invisible intelligence into visible structure",
      plain:  "Translating invisible intelligence into visible structures — this is the work you were quietly trained for your whole life. Architecture taught you spatial logic; AI consulting teaches you systems. The combination is rare.",
      expert: "☿ Mercury ♊ 12H + ♄/♃ 10H + MC ♓. Mercury in its own sign submerged in 12H creates the symbolic-translator cognitive signature. Saturn/Jupiter at MC demand visible structure as output.",
      sources: ["☿ Mercury ♊ 12H", "♃ Jupiter ♈ 10H", "♄ Saturn ♈ 10H", "MC ♓"],
      practice: ["Embedded with one creative studio at a time — not mass consulting.", "Workshops that leave tangible artifacts, not decks."],
    },
    {
      n: "02",
      title: "Soul-tech founder",
      sub: "Income that changes how people relate to themselves",
      plain:  "Building something that generates income while changing how people relate to themselves. MYBC is this exact shape. Products that feel like quiet companions.",
      expert: "MC ♓ + 12H stellium gives the brand-as-mythology signature. ♄ Saturn 10H underwrites multi-year company-building. ♅ Uranus 8H enables unconventional monetization.",
      sources: ["MC ♓", "12H stellium", "♄ Saturn 10H", "♅ Uranus 8H"],
      practice: ["One product, long horizon.", "A small team that shares the vocabulary."],
    },
    {
      n: "03",
      title: "Experience architect",
      sub: "Spatial · digital · ritual design",
      plain:  "Designing environments that transform the people inside them — before they understand why. Retreats, installations, digital onboarding flows.",
      expert: "♀ Venus ♋ 12H + Cancer ASC = sensory-atmospheric authorship. MC ♓ reads as poetic public face. ♂ Mars ♎ 4H = drive rooted in environmental beauty.",
      sources: ["♀ Venus ♋ 12H", "Cancer ASC", "MC ♓", "♂ Mars ♎ 4H"],
      practice: ["Spaces and experiences the body feels before the mind catches up.", "Retreats, installations, branded environments."],
    },
    {
      n: "04",
      title: "Author · essayist",
      sub: "Long-form voice with a recognizable interior temperature",
      plain:  "Your sentences carry a private temperature. People will follow a voice like that for decades. Mercury in Gemini 12H is a lifelong writer's placement.",
      expert: "☿ Mercury ♊ 12H is one of the strongest writer signatures. The 10H stellium says it reaches audience. MC ♓ gives the poetic public mouthpiece.",
      sources: ["☿ Mercury ♊ 12H", "MC ♓", "☉ Sun 10H"],
      practice: ["One essay a month, not one a week.", "A book every three to four years — depth over volume."],
    },
    {
      n: "05",
      title: "Practitioner-teacher",
      sub: "Teach only what you have personally walked",
      plain:  "You teach best when the curriculum is your own scar tissue, distilled. The classroom is a temple when you do this. Avoid teaching what you only read.",
      expert: "♄ Saturn 10H + ♃ Jupiter 10H: authority through earned mastery, not credentialing. MC ♓ dislikes hard-edged guru posture. NN ♌ 12H: transmit the hidden in visible form.",
      sources: ["♄♃ 10H", "MC ♓", "NN ♌ 12H"],
      practice: ["Small cohorts, long arcs — 6 months minimum.", "Material that comes from journals first, decks second."],
    },
  ],

  // ── Body ──────────────────────────────────────────────────────────
  body: {
    constitution: "Wind-dominant with secondary fire",
    blurb: {
      plain:  "A reactive, mobile, light system. You burn through energy fast and recover slowly when stressed. Steady warmth, food, and rhythm are your medicine.",
      expert: "Air 40% / Fire 35% · Cancer ASC · 12H Venus. Wind-pitta in Ayurvedic terms. Nervous system runs hot and cold; HRV variance is high. Earth deficit demands daily grounding.",
    },
    signals: [
      { l: "Cold extremities",       v: "High" },
      { l: "Light, broken sleep",    v: "High" },
      { l: "Bloating under stress",  v: "High" },
      { l: "Jaw tension / TMJ",      v: "High" },
      { l: "Skin reactivity",        v: "Medium" },
      { l: "Adrenal fatigue risk",   v: "Medium" },
      { l: "Inflammation markers",   v: "Low" },
    ],
    regions: [
      { id: "gut",   label: "Gut & digestion",     priority: "High",   note: "Cancer ASC — your #1 health axis. Cooked, warm, slow meals. Avoid raw, cold, hurried eating." },
      { id: "head",  label: "Head & nervous system",priority: "High",   note: "Migraines, jaw tension, racing mind. Daily 4-7-8 breathing + magnesium at bedtime." },
      { id: "lungs", label: "Lungs & throat",       priority: "Medium", note: "Gemini respiratory sensitivity. Humming daily. Steam in winter. No HIIT that stresses breath." },
      { id: "lower", label: "Lower back & kidneys", priority: "Medium", note: "Libra Mars adrenal axis. Restorative yoga + heat over ice for any flare." },
      { id: "skin",  label: "Skin & lymphatics",    priority: "Medium", note: "Cancer lymphatic tendency. Dry brushing + sesame oil massage weekly. Stay hydrated." },
      { id: "pelvic",label: "Pelvic · reproductive",priority: "Watch",  note: "Track cycle. Wood-Tiger overtone (TCM) can cause menstrual irregularity when Liver Qi is blocked." },
    ],
    practices: [
      "Eat warm, cooked food. Stop eating after 19:30.",
      "Bed by 22:30, same time every night including weekends.",
      "Heat over ice for any injury or tension — your Cancer ASC needs warmth.",
      "No HIIT — you will pay double in recovery the next day.",
      "Oil massage (abhyanga) once a week — sesame or almond.",
      "Walk barefoot on earth or grass at least twice a week.",
    ],
  },

  // ── Year ──────────────────────────────────────────────────────────
  year_months: [
    { m: "Jun", y: 26, theme: "Solar return", color: "#1f2125", energy: 8, business: 7, body: 7, love: 7, transit: "Sun ♊ return · Jupiter ♋ ASC", plain: "Your birthday window. Jupiter is still crossing your Ascendant — this is a year of personal expansion. Set the keel for the next twelve months in the first week.", expert: "♃ ♋ crossing ASC · ☉ return on ☿ · 12H Venus by progression" },
    { m: "Jul", y: 26, theme: "Heart-opening", color: "#3a3f4a", energy: 8, business: 6, body: 8, love: 9, transit: "Leo season · Moon home", plain: "Your solar high point extends. Heart-opening, Leo Moon fully on. Maximum magnetism. Creative work, love conversations, embodiment.", expert: "☉ ♌ on NN 12H · ♃ entering ♌ · Leo season" },
    { m: "Aug", y: 26, theme: "Rest & integrate", color: "#2a2a3a", energy: 6, business: 5, body: 9, love: 7, transit: "Virgo season · harvest", plain: "Rest and integrate. Water, nature, travel if possible. The body needs a recharge before the autumn push.", expert: "☉ ♍ 3H · Mars in Leo activating NN" },
    { m: "Sep", y: 26, theme: "Refine & plan", color: "#3a4a3a", energy: 7, business: 9, body: 6, love: 5, transit: "Saturn trine Sun", plain: "Virgo/Libra season — refine, systematize, set the autumn plan. Good for contracts, structures, client work.", expert: "♄ ♓ trine ☉ ♊ · slow constructive transit" },
    { m: "Oct", y: 26, theme: "Deep creative", color: "#4a3a4a", energy: 7, business: 7, body: 6, love: 8, transit: "Venus return · Scorpio", plain: "Major creative and transformational work. A conversation reshapes a key relationship. Pluto energy intensifies creative output.", expert: "♀ return ♎ · ♇ Scorpio season activation" },
    { m: "Nov", y: 26, theme: "Underworld", color: "#2a2a2a", energy: 4, business: 5, body: 5, love: 6, transit: "Pluto direct · Scorpio season", plain: "Low season. Sleep more, decide less. Old grief comes up to be metabolised. This is not failure — it is necessary.", expert: "♇ direct · ♂ in ♏ · low-light nervous system protocol" },
    { m: "Dec", y: 26, theme: "Close chapters", color: "#3a3a4a", energy: 5, business: 5, body: 7, love: 6, transit: "Jupiter direct · Capricorn", plain: "Reflect, close chapters, financial review. Hold the year-end quietly. January is the launch, not December.", expert: "♃ direct · Capricorn IC activation · Sagittarius solar energy" },
    { m: "Jan", y: 27, theme: "Launch", color: "#1f2125", energy: 9, business: 9, body: 7, love: 6, transit: "Jupiter sextile Sun · Aries", plain: "Best month of the year for new public work. Jupiter moves into Leo, activating your North Node. Ship in the first ten days.", expert: "♃ ♌ on NN ♌ 12H · ☉ ♑ sextile ☉ natal · 10H momentum" },
    { m: "Feb", y: 27, theme: "Refine & publish", color: "#3a3f4a", energy: 7, business: 8, body: 6, love: 7, transit: "Mercury direct · publishing", plain: "Polish. Edit. Tighten. Don't start anything new — finish what January started. Teaching and publishing windows open.", expert: "☿ direct after shadow · ♃ ♌ supports creative output" },
    { m: "Mar", y: 27, theme: "Visibility", color: "#4a3a4a", energy: 7, business: 7, body: 7, love: 8, transit: "Sun on MC · Pisces season", plain: "Your public face is most visible. Sun crossing your Midheaven. Use it gently — one careful sentence travels far.", expert: "☉ ♓ on MC · ♀ exalted · Venus support" },
    { m: "Apr", y: 27, theme: "Body reset", color: "#3a4a3a", energy: 8, business: 5, body: 9, love: 6, transit: "Aries season · Mars home", plain: "Spring physical rebuild. Strength training, light fasting, cold-then-warm protocols. The body is ready for more.", expert: "♂ ♈ home · 9H opening · Aries stellium activation" },
    { m: "May", y: 27, theme: "Pre-birthday synthesis", color: "#4a4a3a", energy: 7, business: 7, body: 7, love: 7, transit: "Gemini ingress · solar peak", plain: "The year folds itself into a clear shape. Write it down before the next solar return. Review, synthesize, prepare.", expert: "☿ ♊ home · ☉ pre-return · 12H opening · pre-solar-return review" },
  ],

  year_windows: [
    { label: "Best money window",    range: "Jan 1–15, 2027",      detail: "Jupiter on North Node. Ship product, sign contracts, raise prices." },
    { label: "Best love window",     range: "Jul–Aug 2026",        detail: "Leo season + Jupiter crossing ASC = maximum magnetism and heart-opening." },
    { label: "Avoid big decisions",  range: "Nov 2026",            detail: "Pluto direct + low energy. Sleep on everything for at least 72 hours." },
    { label: "Best rest window",     range: "Aug 2026",            detail: "Post-summer integration. Guard the calendar — this is nervous system medicine." },
  ],

  // ── Love ──────────────────────────────────────────────────────────
  love: {
    blueprint: {
      plain:  "You love with the whole nervous system. Safety is the prerequisite, not the bonus — once you have it, your love is wide, patient, and transformational.",
      expert: "Cancer ASC + 12H Venus · 7H Capricorn, Neptune on cusp. You need ritual + repetition + visible commitment. Avoid avoidants. The right partner is older or steadier inside.",
    },
    needs: [
      { l: "Predictable rhythm",        sub: "Same dinners, same check-ins, same nights — the boring is sacred to your Cancer ASC." },
      { l: "Private language",          sub: "Inside jokes, nicknames, a vocabulary only the two of you speak. Leo Moon needs the mirror." },
      { l: "A long horizon",            sub: "You unfold over years, not weeks. Choose someone willing to wait for the full version." },
      { l: "A steadier nervous system", sub: "Their baseline calm has to be able to meet your storms. Not fix them — meet them." },
      { l: "Being known in shadow",     sub: "12H Venus only truly receives love when the hidden parts are welcomed, not just the bright ones." },
    ],
    activates: [
      "Quiet attention — being fully looked at when you speak.",
      "A made bed. A cooked meal. Small, recurring offerings.",
      "Long walks where neither of you needs to perform.",
      "Being known across moods, not just the bright ones.",
    ],
    depletes: [
      "Mixed signals. Plans that move three times.",
      "Performative ambition without inner life.",
      "People who soften around alcohol — you will match and sink.",
      "Being treated as a project or a cause.",
    ],
    compatibility: [
      { sign: "Capricorn", glyph: "♑", score: "High",   note: "Your 7th-house sign. Quiet authority meets quiet authority. They give structure; you give warmth." },
      { sign: "Scorpio",   glyph: "♏", score: "High",   note: "Pluto resonance. The depth matches — creative, sexual, emotionally transformational." },
      { sign: "Taurus",    glyph: "♉", score: "High",   note: "Earth steadies your air-fire. They feed you slowly, beautifully. The physical world opens." },
      { sign: "Pisces",    glyph: "♓", score: "Strong", note: "MC resonance. A shared inner world. Watch for shared escapism patterns." },
      { sign: "Aquarius",  glyph: "♒", score: "Tricky", note: "Mirrors your South Node. You love their mind. They forget to come home." },
      { sign: "Gemini",    glyph: "♊", score: "Twin",   note: "Like dating yourself — fast, brilliant, and ultimately exhausting without Earth." },
    ],
  },

  // ── Nutrition ─────────────────────────────────────────────────────
  nutrition: {
    principle: {
      plain:  "Warm, cooked, slow. Your gut runs cold and your nervous system runs fast — food is one of the few levers that calms both simultaneously.",
      expert: "Wind-pitta (Vata-Pitta) Ayurvedic constitution. Favor warming, oily, grounding. Reduce raw, cold, astringent. Largest meal at noon. 14-16h fasting window only.",
    },
    groups: [
      {
        label: "Eat freely",
        tone: "eat",
        items: [
          "Soups, stews, bone broth — warm and mineral-rich",
          "Wild salmon, sardines, pastured eggs, white fish",
          "Cooked greens with ghee or olive oil (spinach, chard, kale)",
          "Root vegetables — sweet potato, carrot, parsnip, beet",
          "Soaked walnuts, almonds, pumpkin seeds",
          "Ghee, sesame oil, olive oil, avocado",
          "Ginger, turmeric, cinnamon, cardamom, fennel, cumin",
          "Berries (stewed or room temperature), seasonal fruit",
        ],
      },
      {
        label: "In moderation",
        tone: "limit",
        items: [
          "Coffee — one small cup before 10:00, never after 13:00",
          "Salads — only at lunch, only in warm months",
          "Wine — one glass maximum, with food, once a week",
          "Dairy — small amounts, always warmed (kefir, ghee, cheese)",
          "Beans and legumes — only if well-cooked with digestive spices",
          "Gluten — experiment with removal and re-introduction",
        ],
      },
      {
        label: "Avoid",
        tone: "avoid",
        items: [
          "Cold smoothies and iced drinks on an empty stomach",
          "Raw food after sunset or as the main meal",
          "Refined sugar in the morning",
          "Ultra-processed seed oils (canola, sunflower, soybean)",
          "Alcohol more than once a week (Neptune dissolution signature)",
          "Skipping meals or eating in a hurry",
          "Eating while working, scrolling, or emotionally activated",
        ],
      },
    ],
    rhythm: [
      { time: "On waking",   what: "500 ml warm water + pinch Celtic sea salt + juice of half a lemon" },
      { time: "10:30–11:00", what: "First meal — protein-forward, warm, cooked (eggs, avocado, cooked greens)" },
      { time: "13:30",       what: "Largest meal — protein + roasted root veg + grain + fermented side" },
      { time: "16:30",       what: "Adaptogen tea — ashwagandha or lemon balm, small snack if needed" },
      { time: "19:00–19:30", what: "Light dinner — bone broth, fish or chicken, roasted veg" },
      { time: "21:00",       what: "Stop eating. Chamomile tea + magnesium glycinate in water before bed." },
    ],
  },

  // ── Rituals ───────────────────────────────────────────────────────
  rituals_days: [
    { day: "Monday",    label: "Threshold",   ruler: "☽", ritual: "Set the week's one true intention. Write it on paper. Place it where you'll see it all week.", detail: "Cancer ASC week needs an anchor on day one — without it the week scatters." },
    { day: "Tuesday",   label: "Forge",       ruler: "♂", ritual: "Move hard, but only once. Pilates reformer, climbing, or a long walk in cold air.", detail: "Mars day. Your only high-intensity slot. Do not stack workouts on consecutive days." },
    { day: "Wednesday", label: "Threadwork",  ruler: "☿", ritual: "Deep-work block. No meetings before noon. Write or build the hardest thing on the list.", detail: "Mercury day — your home planet. The week's most cognitively generous window." },
    { day: "Thursday",  label: "Open hand",   ruler: "♃", ritual: "Reach out to one person you've been meaning to contact. No agenda — just presence.", detail: "Jupiter day. Relationships compound. Small contact this day pays back monthly." },
    { day: "Friday",    label: "Sensorium",   ruler: "♀", ritual: "One sensory pleasure made deliberate — a long meal, a bath, live music, a walk by water.", detail: "Venus day. Your 12th-house Venus needs ritual delight, not novelty or stimulation." },
    { day: "Saturday",  label: "Container",   ruler: "♄", ritual: "Tidy one room. Close one open loop. Review and set Monday's intention draft.", detail: "Saturn day. Structure begets freedom. Monday depends on what you do today." },
    { day: "Sunday",    label: "Soft border",  ruler: "☉", ritual: "No work. No screens before 10:00. Long walk, cooked meal, early bed.", detail: "Sun day. Hard rest. This is when your nervous system actually catches up." },
  ],

  rituals_seasonal: [
    { label: "New moon",     cadence: "Monthly",      detail: "Bath + salt + white candle. Write one seed intention per life area. Read aloud. Sleep early." },
    { label: "Full moon",    cadence: "Monthly",      detail: "Write what you're releasing. Burn it. Walk under the moon near water. Journal raw." },
    { label: "Solstice",     cadence: "Twice yearly", detail: "Cook for one trusted person. A long meal with no agenda. Mark the turning." },
    { label: "Solar return", cadence: "Yearly",       detail: "Write a letter to next-year's self. Open it on the same date next year." },
  ],

  // ── Mind ──────────────────────────────────────────────────────────
  mind: {
    signature: {
      label:  "Symbolic-associative",
      plain:  "You think in webs, not lines. Synthesis comes faster than analysis. You sometimes know things before you know how you know them.",
      expert: "Mercury in Gemini in the 12th — Mercury rules its sign but is submerged. Layered symbols, metaphor, dream-logic, and pattern association replace linear argument. Higher resolution on synthesis, lower tolerance for rigid sequence.",
    },
    strengths: [
      { l: "Pattern recognition across distant domains", n: "01" },
      { l: "Metaphorical and symbolic thinking",         n: "02" },
      { l: "Quick idea generation and lateral connection",n: "03" },
      { l: "Multilingual and multimodal fluency",        n: "04" },
      { l: "Visual-spatial cognition (architectural)",   n: "05" },
      { l: "Intuitive leaps — 12th-house downloads",     n: "06" },
      { l: "Deep reading and symbolic interpretation",   n: "07" },
    ],
    friction: [
      "Linear argumentation under pressure",
      "Memorization of disconnected, context-free facts",
      "Repetitive detail work with no symbolic layer",
      "High-pressure verbal debate with hostile parties",
      "Tasks requiring rigid, unchanging sequencing",
      "Environments with constant interruption",
      "Explaining intuitive reasoning on demand",
    ],
    windows: [
      { time: "06:30 – 09:00", label: "Capture",    note: "First drafts and idea capture before input enters. The mind is most receptive and unfiltered." },
      { time: "09:30 – 11:30", label: "Deep work",  note: "Writing, strategy, complex analysis. The single most productive block of the day." },
      { time: "15:00 – 16:30", label: "Edit",       note: "Secondary focus — refining, polishing, executing details from the morning session." },
      { time: "20:00 – 22:00", label: "Creative",   note: "Most mystically productive window. 12th-house activation after sunset. Best for generative creative work." },
    ],
    never: [
      "Multitask during deep work (Gemini trap — feels productive, produces nothing)",
      "Consume content in the first hour after waking",
      "Make major decisions late at night (12th-house dream logic skews reality)",
      "Argue when tired — Mercury 12H will wound without intending to",
      "Memorize by repetition — use association and imagery instead",
      "Stay on one project more than 3 hours without a different-modality break",
    ],
  },

  // ── Sport ─────────────────────────────────────────────────────────
  sport: {
    philosophy: {
      plain:  "Beautiful, rhythmic, flow-based. Your body resents grinding gym culture. It responds to flow, grace, and precision — with controlled intensity, occasionally.",
      expert: "Mars in Libra in the 4th + Jupiter/Saturn in Aries 10th + Leo Moon. Movement must be beautiful, rhythmic, and either solitary-deep or elegantly social. The Leo Moon wants to feel radiant; the Libra Mars wants symmetry.",
    },
    best: [
      { l: "Pilates (reformer)",       n: "Precision, length, core — perfect Libra Mars expression. Sets the week's symmetry." },
      { l: "Yoga — Vinyasa or Hatha",  n: "Avoid overly dissolving schools. You don't need more dissolution; you need grounded flow." },
      { l: "Pole dance or barre",      n: "Leo Moon expression + Libra Mars aesthetics. Where your radiance comes out physically." },
      { l: "Swimming",                 n: "Water soothes Cancer ASC. One of your most powerful recovery modalities." },
      { l: "Dance (any style)",        n: "Where your Leo Moon fully lights up. Non-negotiable joy-movement." },
      { l: "Hiking in nature",         n: "12th-house and Cancer ASC replenishment. Ideally near water, without headphones for half." },
      { l: "Strength training 2×/week",n: "Posterior chain + bone loading for Saturn-Aries axis. Moderate weight, precise form." },
    ],
    avoid: [
      "CrossFit and high-volume HIIT — overwhelms the nervous system and adrenal axis",
      "Long-distance running as primary sport — drains Cancer ASC energy",
      "Competitive team sports as main practice — Libra Mars prefers partnership, not combat",
      "Heavy bodybuilding — works against your frame and energy signature",
    ],
    week: [
      { d: "Mon", l: "Pilates reformer",           m: "50 min",      n: "Classical style. Symmetry and precision to start the week. Magnesium bath in the evening." },
      { d: "Tue", l: "Strength — lower body",      m: "45 min",      n: "Squats, deadlifts, hip thrusts, rows. Saturn in Aries wants structural strength. Finish with 10 min mobility." },
      { d: "Wed", l: "Yoga or swim",               m: "60 / 40 min", n: "Vinyasa or swimming. Midweek water-and-flow reset. 12th-house replenishment." },
      { d: "Thu", l: "Strength — upper + core",    m: "45 min",      n: "Press, pull, carry. Technical lifts on Mercury day. Finish with breathwork." },
      { d: "Fri", l: "Dance · pole · barre",       m: "60 min",      n: "Leo Moon day — express, radiate, be seen. This is non-negotiable." },
      { d: "Sat", l: "Long nature walk or hike",   m: "90–120 min",  n: "Slow pace. Ideally near water. No headphones for at least half." },
      { d: "Sun", l: "Rest or restorative yoga",   m: "— / 30 min",  n: "The discipline here is not pushing. Cancer ASC and Moon 12H need the full day." },
    ],
  },

  // ── Chinese ───────────────────────────────────────────────────────
  chinese: {
    animal:       "Tiger",
    element:      "Earth",
    polarity:     "Yang",
    range:        "28 Jan 1998 – 15 Feb 1999",
    archetype: {
      plain:  "A rare combination. Most Tigers burn hot and scatter; the Earth Tiger builds. You are a builder-warrior — the Tiger's boldness and magnetism, tempered by Earth's steadiness and patience.",
      expert: "Yang Earth Tiger with Wood overtones. The entrepreneurial archetype: leads enterprises, not battles. Naturally charismatic, protective, allergic to imposed routine. Needs freedom of movement or becomes restless and self-destructive.",
    },
    traits: [
      "Charismatic and deeply protective of loved ones",
      "Allergic to routine imposed by others — must create the structure from within",
      "Deeply independent · needs freedom to move or becomes caged",
      "Capacity to finish, endure, and build durable things (the Earth gift)",
    ],
    tcm: [
      { organ: "Spleen · Stomach", el: "Earth", note: "Your digestive axis. Matches Cancer ASC directly. When strong: stable energy, immunity. When weak: fatigue, bloating, worry, damp accumulation." },
      { organ: "Liver · Gallbladder", el: "Wood", note: "Tiger's Wood overtone. When blocked: tension, headaches, irritability, menstrual irregularity. Keep the Liver Qi flowing." },
      { organ: "Lungs",              el: "Metal", note: "Gemini Sun overlap. Respiratory sensitivity. Holds grief. Humming and breath work protect this axis." },
    ],
    emotions: [
      { e: "Worry · overthinking", o: "Spleen" },
      { e: "Anger · frustration",  o: "Liver" },
      { e: "Sadness · grief",      o: "Lung" },
    ],
    years: [
      { y: "2026", name: "Yang Fire Horse", tone: "strong", n: "Harmonious with Tiger. Visibility, movement, passion projects. Launch year. Watch overexertion and overheating." },
      { y: "2027", name: "Yin Fire Goat",   tone: "soft",   n: "Softer, more relational. Partnership, creative collaboration, slowing down." },
      { y: "2028", name: "Yang Earth Monkey",tone: "hard",  n: "Tiger's opposite — the most challenging year ahead. Build reserves in 2026–27." },
      { y: "2029", name: "Yin Earth Rooster",tone: "soft",  n: "Recovery and refinement. Systems, craft, reputation from previous work." },
      { y: "2030", name: "Yang Metal Dog",   tone: "strong", n: "Dog is a strong Tiger ally. Loyalty, building, family, home-making. Stabilizing." },
    ],
  },

  // ── Gut ───────────────────────────────────────────────────────────
  gut: {
    principle: {
      plain:  "Your gut is not one pillar among many. It is the pillar. Immunity, mood, skin, sleep, hormones, and cognition all flow through this one.",
      expert: "Cancer ASC rules the stomach. Venus in Cancer in the 12th amplifies the gut–emotion connection. The Moon (your chart ruler) in the 12th means the gut processes not just food but emotion, ambient energy, and unspoken tension.",
    },
    rituals: [
      { time: "On waking",     what: "Warm water + lemon + pinch of Celtic sea salt — minerals first, before anything else" },
      { time: "Before meals",  what: "3 slow breaths, hands on belly, a moment of gratitude — activates vagus nerve and digestive secretion" },
      { time: "While eating",  what: "Chew each bite 20–30 times. No screens, no work, no emotional activation. Seated." },
      { time: "Before 20:00",  what: "Last meal of the day. Cancer ASC needs 3 full hours before sleep for digestion." },
      { time: "Before sleep",  what: "10 min clockwise belly massage with warm sesame or coconut oil" },
    ],
    warnings: [
      "Bloating within 30 min of eating",
      "Brain fog 1–2 hours post-meal",
      "Skin breakouts around jaw and chin",
      "Sudden cravings for sugar or salt",
      "Afternoon mood crash",
      "Waking between 1:00 and 3:00 AM (TCM liver-gallbladder window)",
      "Cold hands and feet",
      "Emotional flooding that feels physically located in the stomach",
    ],
    reset48: [
      { l: "Eat only",          n: "Bone broth, steamed vegetables, well-cooked rice, stewed apples, ginger tea" },
      { l: "Avoid completely",  n: "Raw food, cold food, caffeine, alcohol, sugar, anything rushed" },
      { l: "Daily",             n: "Warm Epsom salt bath · belly massage morning and evening" },
      { l: "After every meal",  n: "Legs-up-the-wall for 15 min — aids lymphatic return and vagal tone" },
      { l: "Social",            n: "No obligations. 12th-house solitude. This is medicine." },
    ],
    testing: [
      { l: "Full stool analysis (GI-MAP)", cadence: "Every 2 years" },
      { l: "Food sensitivity panel",       cadence: "If symptoms persist >3 months" },
      { l: "SIBO breath test",             cadence: "If bloating is chronic" },
      { l: "hs-CRP · homocysteine",        cadence: "Annually with blood work" },
    ],
  },

  // ── Report prose (key excerpts per section) ───────────────────────
  report_content: {
    "01": [
      ["p", "Your chart was cast for 10 June 1998, 08:03 in Verviers, Belgium. Placidus house system."],
      ["h", "Planetary positions"],
      ["dl", [
        ["Sun", "19°12' Gemini · 10th house · Mutable Air. Identity tied to visibility, communication, and public contribution."],
        ["Moon", "27°05' Leo · 12th house · Fixed Fire. Regal, dramatic, warm — but tucked into the house of solitude and the unseen."],
        ["Ascendant", "14°48' Cancer · Cardinal Water. You meet life through feeling first, logic second."],
        ["Midheaven (MC)", "24°17' Pisces · Mutable Water. Vocation flows through imagination, healing, and symbolism. Career is not a ladder — it is a tide."],
        ["Mercury", "6°41' Gemini · 12th house. Genius that speaks in symbols, dreams, downloads — not linear logic."],
        ["Venus", "2°54' Cancer · 12th house. Love lives in the hidden sanctuary. Devotional, self-protective, mystical."],
        ["Mars", "1°28' Libra · 4th house. Drive is relational, aesthetic, rooted in the home base."],
        ["Jupiter", "24°33' Aries · 10th house. Expansive fire at the career summit. A born builder of new visible territory."],
        ["Saturn", "29°48' Aries · 10th house (anaretic degree). A crisis degree of identity-forging. Heavy discipline around visibility and authority."],
        ["Uranus", "12°46' Aquarius retrograde · 8th house. Revolutionary intuition in the house of transformation."],
        ["Neptune", "2°36' Aquarius retrograde · 7th house. Dreams project onto partners."],
        ["Pluto", "7°44' Sagittarius retrograde · 5th house. Deep transformation through creativity, romance, risk."],
        ["North Node", "26°13' Leo · 12th house. The soul's growth direction: the radiant self, expressed from inside the hidden room."],
        ["South Node", "26°13' Aquarius · 6th house. Karmic comfort zone: over-serving, over-systematizing, clinical detachment."],
      ]],
      ["h", "Element distribution"],
      ["ul", ["Air 40% — Sun, Mercury, Mars, Uranus, Neptune, South Node", "Fire 35% — Moon, Jupiter, Saturn, Pluto, North Node", "Water 20% — Ascendant, MC, Venus", "Earth 5% — minimal"]],
      ["p", "A /wind-and-flame/ chart. Thought and inspiration dominate; the body (Earth) is the underdeveloped axis. You are more likely to forget to eat than to forget an idea."],
      ["h", "The chart's two poles"],
      ["p", "A brilliantly public 10th house (Sun, Jupiter, Saturn) paired with a mystical 12th house (Moon, Mercury, Venus, North Node). You are built to channel the unseen into the seen — that is the chart's central instruction, and every other chapter unfolds from it."],
    ],
    "02": [
      ["p", "Fifteen things you are unusually good at, ten places where the same wiring trips you up. Strengths and weaknesses are not opposites in astrology — they are the same trait read in two different lights."],
      ["h", "15 strengths"],
      ["ol", [
        "/Visionary synthesis./ Seeing a future others haven't imagined and drawing the bridge to it.",
        "/Symbolic cognition./ Reading patterns, archetypes, and hidden meaning others miss.",
        "/Magnetism./ People feel drawn to you without knowing why.",
        "/Creative courage./ Starting things no one else dares to start.",
        "/Healing presence./ People tell you things they haven't told anyone.",
        "/Multi-domain fluency./ Moving between architecture, AI, and mysticism without losing coherence.",
        "/Pattern-finding across time./ Finding the thread that runs through generations.",
        "/Aesthetic intelligence./ Seeing when something is off visually before you can articulate why.",
        "/Resilience after collapse./ Disruption as redirection.",
        "/Teaching through metaphor./ Complex ideas become felt, not just known.",
        "/Leadership by radiance./ Leading by being, not by commanding.",
        "/Entrepreneurial instinct./ Seeing market gaps before others name them.",
        "/Emotional perceptiveness./ Feeling the room within seconds.",
        "/Long-term architecture./ Building structures designed to last decades.",
        "/Ancestral bridge./ Carrying forward what your lineage couldn't finish.",
      ]],
      ["h", "10 weaknesses"],
      ["ol", [
        "/Overextension./ Mars opposite Jupiter. Starting more than you can finish. Antidote: quarterly pruning.",
        "/Emotional porosity./ Moon opposite Neptune. Taking on others' moods. Antidote: hourly 'is this mine?' check.",
        "/Perfectionist paralysis./ Saturn anaretic 10th. Over-polishing, not shipping. Antidote: external deadlines with witnesses.",
        "/Withdrawal under conflict./ Cancer ASC + Venus 12th. Going silent. Antidote: 48-hour rule — process, then speak.",
        "/Romantic idealization./ Neptune 7th. Seeing potential, not reality. Antidote: 90-day observation rule.",
        "/Escapism./ Neptune opposite Moon. Dissolution. Antidote: name the pattern early, build structure into vulnerable days.",
        "/Rumination./ Mercury 12th. Replaying conversations for days. Antidote: evening brain-dump journaling.",
        "/Restlessness./ Gemini Sun + Sagittarius Pluto. Urge to quit and start over. Antidote: distinguish redirection from escape.",
        "/Under-grounding./ 5% Earth. Forgetting to eat, disconnecting from the body. Antidote: daily body-anchoring ritual.",
        "/Self-criticism./ Sun square Saturn (wide). Internal critic that diminishes real achievements. Antidote: weekly written evidence log.",
      ]],
      ["h", "Shadow sides"],
      ["p", "/Escapism patterns:/ sudden urges to move countries, quit all projects, dissolve into a relationship, scroll until 2 AM. Early warning: you start to romanticize leaving."],
      ["p", "/Martyr-victim loop:/ Cancer ASC + 6th-house South Node. Over-serve, then resent, then withdraw, then self-punish for the withdrawal. Early warning: 'nobody sees how hard I work.'"],
      ["p", "/Shadow manipulation:/ the 12th-house Venus can seduce without conscious intent; the Leo Moon can perform wounded royalty. Early warning: you find yourself /crafting/ messages rather than sending them straight."],
    ],
    "03": [
      ["p", "Mercury in Gemini in the 12th house is one of the most unusual Mercury placements. You think in /layered symbols, metaphors, images, dreams, and associations/ rather than linear argument."],
      ["h", "Cognitive signature"],
      ["p", "When forced into linear or formal communication, you underperform. When you speak from the symbolic-intuitive layer — writing, art, storytelling, teaching through metaphor — you are genuinely exceptional. You think in webs, not lines."],
      ["h", "Peak creative windows"],
      ["ul", ["20:00–22:00 — your most mystically productive window", "Early morning before 09:00 — first drafts and idea capture", "Full moons — schedule major creative projects around them"]],
      ["h", "What this brain should never do"],
      ["ul", ["Multitask during deep work (the Gemini trap)", "Consume content in the first hour after waking", "Make major decisions late at night", "Argue when tired", "Stay on one project for more than 3 hours without a modality break"]],
    ],
    "04": [
      ["h", "Constitution"],
      ["p", "/Wind-dominant with secondary fire./ Cancer rising with Venus in Cancer near the ASC gives a soft, rounded, luminous facial structure — full cheeks, expressive eyes, skin that holds moisture beautifully when healthy."],
      ["h", "Optimal trained body type"],
      ["p", "/Lean-strong feminine./ Focus on lymphatic flow, core stability, and posterior chain strength. NOT a bulked frame — think dancer-Pilates-yoga body with strength training twice a week to protect bone density."],
      ["h", "Nervous system profile"],
      ["p", "Highly sensitive, porous, wind-type. On the HSP spectrum, you would score in the top 10–15%. The Moon–Neptune opposition, Moon square Uranus, and 12th-house stellium combine to create a nervous system that picks up environmental and emotional data at extremely high resolution."],
      ["h", "Warning signs of overload (in order)"],
      ["ol", ["Mild insomnia or vivid disturbed dreams", "Jaw clenching, teeth sensitivity", "Bloating, digestive sluggishness", "Emotional flooding — crying that comes from nowhere", "Brain fog, forgetting words mid-sentence", "Sudden urge to flee, quit everything, move countries"]],
    ],
    "05": [
      ["p", "Your chart has minimal Earth (5%), so your relationship to food is not instinctive — it needs to be /consciously structured/. Water + Fire + Air dominate, which creates a digestive fire easily doused (by cold foods) or overwhelmed (by heavy ones)."],
      ["h", "Core principle"],
      ["p", "/Warm, cooked, mineral-rich, fiber-moderate, protein-consistent, hydrating./ Think Mediterranean-meets-Ayurvedic-Pitta-Vata-pacifying."],
      ["h", "Fasting window"],
      ["p", "14–16 hours overnight. Eating window roughly 10:00 to 20:00. /Longer fasts (20h+, OMAD) are specifically wrong for your chart./ They destabilize the nervous system and crash the Cancer ASC digestive axis."],
      ["h", "Addiction risks (named, with care)"],
      ["p", "Your chart carries a real escapism signature. The substances most likely to hook you: alcohol (especially wine, in romantic settings — the Venus-in-Cancer trap), cannabis (Neptune softness that feels like coming home but is dissociation), workaholism (Saturn 10th), sugar as emotional medicine. /The protection is structure, not willpower./"],
      ["note", "All supplement recommendations should be discussed with a qualified physician before starting — especially anything marked Tier 1."],
    ],
    "06": [
      ["h", "Philosophy"],
      ["p", "Mars in Libra in the 4th + Jupiter/Saturn in Aries 10th + Leo Moon. Movement must be /beautiful, rhythmic, and either solitary-deep or elegantly social./ Your body resents grinding gym culture."],
      ["h", "7-day training week"],
      ["dl", [
        ["Monday", "Pilates reformer, 50 min. Classical style. Mars in Libra needs the symmetry to start the week."],
        ["Tuesday", "Strength training, 45 min. Lower body + posterior chain. Saturn in Aries wants the structural challenge."],
        ["Wednesday", "Yoga or swimming. Midweek water and flow reset. 12th-house replenishment."],
        ["Thursday", "Strength training, 45 min. Upper body + core. Mercury-day energy suits technical lifts."],
        ["Friday", "Dance, pole, or barre, 60 min. Leo Moon day — express, radiate, be seen. Non-negotiable."],
        ["Saturday", "Long nature walk or hike, 90–120 min. Ideally near water. No headphones for at least half."],
        ["Sunday", "Full rest or gentle restorative yoga. The discipline here is not pushing."],
      ]],
    ],
    "07": [
      ["p", "Cancer rising governs the stomach directly. Venus in Cancer in the 12th amplifies the gut–emotion connection. The Moon (your chart ruler) in the 12th means the gut absorbs not just food but emotion, ambient energy, and unspoken tension. /For you, gut health is not one pillar among many. It is the pillar./"],
      ["h", "The gut-brain-emotion connection"],
      ["p", "When you suppress an emotion, it lodges in the stomach within hours. When you spend time with someone whose energy is wrong for you, you feel it in the gut the next day. When you break your own boundaries to please someone, the gut protests with bloating, reflux, or sluggishness. This is the feedback loop to honor."],
      ["h", "Emergency reset protocol"],
      ["ul", ["48 hours of simple cooked foods: bone broth, steamed vegetables, well-cooked rice, stewed apples, ginger tea", "No raw, no cold, no caffeine, no alcohol, no sugar", "Warm baths with Epsom salts daily", "10 min belly massage morning and evening", "No social obligations — 12th-house solitude", "Usually resets in 3–5 days"]],
      ["note", "Discuss all of this with a functional medicine practitioner who knows your history."],
    ],
    "08": [
      ["p", "Mercury in Gemini in the 12th house creates a /symbolic-associative/ cognitive style that is extremely rare. Your brain makes unusual connections between distant domains. You are better at synthesis than analysis."],
      ["h", "Ideal learning environment"],
      ["ul", ["Quiet or low-stimulus background — soft instrumental, not silence", "Beautiful physical space with natural light", "Physical books and notebooks alongside digital", "Freedom to take frequent short breaks", "One subject deep-dived at a time"]],
      ["h", "Neuroplasticity protocol"],
      ["ul", ["20 min of a fundamentally new skill daily", "20 min of reading outside your field", "Handwriting practice (3–5 min)", "10 min of novel physical movement pattern", "One full day per week in a new environment", "30 min of complete boredom — no phone, no task"]],
    ],
    "09": [
      ["p", "Fifteen things you are unusually good at, ten places where the same wiring trips you up. Strengths and weaknesses are not opposites — they are the same trait read in two different lights."],
      ["h", "Shadow patterns (the uncomfortable truths)"],
      ["p", "/Escapism:/ sudden urges to move countries, quit all projects, dissolve into a relationship. Intensifies around Pisces/Virgo transits and before major launches. Early warning: you start to romanticize leaving."],
      ["p", "/Martyr-victim loop:/ Cancer ASC + 6th-house South Node. You over-serve, then resent, then withdraw. Early warning: a felt sense of 'nobody sees how hard I work.'"],
      ["p", "/Shadow manipulation:/ the 12th-house Venus can seduce without conscious intent. Early warning: you find yourself crafting messages rather than sending them straight."],
      ["h", "When 2+ of these show up together"],
      ["ul", ["Sleep disruption 3+ nights in a row", "Avoidance of one specific person or conversation", "Wine becoming 'part of the routine'", "A sudden, intense attraction to a new project that would require abandoning a current one", "A vague feeling that you are 'playing a role'"]],
      ["p", "Pull the emergency brake. Clear 48 hours. Call the people who see you clearly."],
    ],
    "10": [
      ["p", "Ten paths your chart points at most clearly, and the handful it warns against. It is not a job list — it is a /shape-of-work/ list."],
      ["h", "North Node mission"],
      ["p", "North Node in Leo, 12th house. Your soul mission is to bring the light of the hidden self into the visible world — but from a place of /solitude, devotion, and inner authority/, not from external approval. Move toward: creative visibility that emerges from inner silence. Move away from: invisible labor and over-serving the collective at the cost of your own luminosity."],
      ["h", "Current life phase"],
      ["p", "You are at the /threshold/ of the first Saturn return (late 2026–early 2028). The architecture chapter is closing or changing shape; the consulting/entrepreneurial chapter is opening; the spiritual-product chapter is crystallizing. This is not overwhelm. This is Saturn asking you to choose."],
      ["h", "Saturn cycle timeline"],
      ["dl", [
        ["First Saturn return", "Age 28–30 — you are entering this now (late 2026 through 2028). The most important career-forging window of the first half of life."],
        ["Saturn opposite Saturn", "Around age 43–44. Mid-life recalibration."],
        ["Second Saturn return", "Age 58–60. Legacy phase."],
      ]],
    ],
    "11": [
      ["h", "Ideal partner profile"],
      ["p", "7th house Capricorn with Neptune on the cusp. The 7th house in Capricorn wants a partner who is /grounded, structured, quietly ambitious, emotionally mature/ — and who also carries /a rich inner world, spiritual depth, and artistic sensibility/. Think: the architect-philosopher, the entrepreneur with a meditation practice, the craftsman-poet. Probably older, or at minimum older-in-soul."],
      ["h", "Attachment style and healing path"],
      ["p", "You likely carry an /anxious-preoccupied/ or /anxious-avoidant/ blend. The Cancer ASC + Venus 12th wants closeness; the Uranus 8th + Gemini Sun needs freedom. Healing path: secure base building. A partner who is consistent, transparent, unhurried, and capable of holding your withdrawals without taking them personally."],
      ["h", "Red flags in partners"],
      ["ul", ["Vague about their past, finances, or commitments (Neptune 7th trap)", "They need you to 'save' them — you will, and lose yourself", "They diminish your mystical or spiritual life", "Their body language softens around alcohol — you will match and sink", "They can't handle your withdrawals without punishing you for them"]],
      ["h", "Friendship patterns"],
      ["p", "A small, deep inner circle (3–5 people), not wide networks. Your 11th house is in Taurus, empty — you build friendships slowly, through tangible trust. Protect at least one evening per week for pure solitude — this is how your 12th-house stellium replenishes."],
    ],
    "12": [
      ["p", "The moon moves through a new sign every 2–2.5 days. Each window has a different energetic quality for you, based on how that sign activates your natal chart."],
      ["h", "How to use these scores"],
      ["ul", ["Energy — how much push the day gives you", "Business — clarity and capacity for focused, transactional work", "Body — the day's gift for physical practice", "Social — your capacity for being with people without depleting"]],
      ["p", "The full 52-week calendar follows this same format. Once you have read two or three months, you will start to feel the shape without needing to look."],
    ],
    "13": [
      ["h", "Cold and heat therapy"],
      ["p", "Your nervous system is /not/ built for dramatic cold plunging. Moon opposite Neptune + Moon square Uranus = a nervous system that destabilizes under shock. Modified protocol: cold shower finish (30–60 seconds) after a warm shower, 3–4x per week. Sauna 2–3x per week at 70–85°C. /Always heat first, then cool finish./ Your Cancer ASC needs the warmth container."],
      ["h", "Breathing techniques"],
      ["dl", [
        ["Activation (morning, low energy)", "Wim Hof-style light breathing — 30 fast breaths, hold on exhale, 3 rounds. Use sparingly; never in late afternoon."],
        ["Stress relief (midday, after hard calls)", "Physiological sigh — double inhale through nose, one long exhale through mouth, 10 repetitions. Fastest known cortisol drop."],
        ["Vagus activation (evening)", "4-7-8 breath — inhale 4 seconds, hold 7, exhale 8 — for 8 rounds. Made for your chart."],
        ["Creativity (before creative work)", "Coherent breathing — 5.5 seconds in, 5.5 seconds out, for 10 minutes. Opens the 12th-house channel."],
      ]],
      ["h", "Blood panel — every 6 months"],
      ["ul", ["Complete blood count", "Ferritin, serum iron (target ferritin 50–100 ng/mL)", "Vitamin D (25-OH) — target 50–80 ng/mL", "B12 (active), folate, homocysteine (target hCY under 8)", "Magnesium RBC (not serum)", "Full thyroid: TSH, free T3, free T4, reverse T3, TPO antibodies", "hs-CRP (under 1)", "HbA1c, fasting glucose, fasting insulin (HOMA-IR under 1.5)", "Sex hormones (cycle day 3 and day 21)", "4-point cortisol or DUTCH test annually"]],
    ],
    "14": [
      ["p", "The Chinese reading of the same birth moment. BaZi gives you four pillars — year, month, day, hour — each with an animal and an element. Where the systems agree, the trait is doubly true."],
      ["h", "Yang Earth Tiger"],
      ["p", "A rare combination. Most Tigers burn hot and scatter; the Earth Tiger /builds/. You are a builder-warrior — boldness and magnetism tempered by Earth's steadiness and patience. An /entrepreneurial archetype/ in Chinese thought: the person who leads an enterprise rather than a battle."],
      ["h", "TCM health implications"],
      ["ul", ["Earth governs Spleen and Stomach — your digestive axis (matches Cancer ASC directly)", "Tiger's Wood overtone influences Liver and Gallbladder (detox, emotional flow, menstrual cycle)", "Your pattern: the over-thinker who suppresses anger into stomach tension and grief into lung tightness"]],
      ["h", "Next four years"],
      ["dl", [
        ["2026 · Yang Fire Horse", "Horse is harmonious with Tiger. Strong year — visibility, movement, career breakthroughs. Launch year. Watch overexertion."],
        ["2027 · Yin Fire Goat", "Softer, relational. Good for partnerships and creative collaboration."],
        ["2028 · Yang Earth Monkey", "Tiger's opposite — the most challenging year. Build reserves in 2026–27. Overlaps with Saturn return culmination."],
        ["2029 · Yin Earth Rooster", "Recovery and refinement. Systems, craft, reputation."],
        ["2030 · Yang Metal Dog", "Dog is Tiger's strong ally. Loyalty, building, family, home. Stabilizing."],
      ]],
    ],
    "15": [
      ["p", "Current major transits converging on your chart in May 2026:"],
      ["h", "Saturn crossing your Midheaven"],
      ["p", "This is the single most important transit of your current life phase. Saturn crossing the Midheaven (24° Pisces) marks the consolidation of vocation — the shift from preparation to manifestation. This is why the questions of 'what career,' 'what identity,' and 'what business' have been so live."],
      ["h", "Jupiter in Cancer — through mid-2026"],
      ["p", "Jupiter crossing your Ascendant expands physical presence, confidence, and personal magnetism. This is a rare benefit transit for visibility and embodiment. /Ride it./"],
      ["h", "Saturn Return — late 2026 to early 2028"],
      ["p", "Saturn returns to its natal position at 29° Aries. The full return spans roughly 18–24 months. Its gift: clarity about what you are actually here to build. Its challenge: the collapse of anything that was not truly yours."],
      ["h", "Current life phase archetype"],
      ["p", "The Threshold. You are between the apprentice and the architect. The architecture is already in your hands; what is being built now determines the shape of the next three decades."],
      ["h", "Closing"],
      ["p", "You are a lighthouse built on soft earth — slow to anchor, late to light, but once the flame is lit and the foundation has found the rock beneath the sand, every ship within fifty miles will see you from the dark."],
    ],
  },
};

export const DEMO_REPORT: Report = {
  id: "demo-report",
  user_token: "demo",
  generation_status: "complete",
  data: DATA,
  generated_at: "2026-04-21T10:00:00Z",
  created_at: "2026-04-21T09:00:00Z",
};
